Page/Page/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('switch.urls'), ),
        
]

"""---- urls.static ---- """
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Page/switch/urls.py
from django.urls import path
from .views import *
"""
#- Bu 2 ferqli url ucun isdifade olunmasi 

#- daha doqrusu /users/create/
# ve /advertisement/create/



"""
app_name = "switch" 

urlpatterns = [
    path(
        '',
        home,
        name="home-anasehife" 
    ),
    path(
        'card-details/',
        card_details,
        name="card-details" 
    ),
    # path(
    #     'create/',
    #     home,
    #     name="create" 
    # ),
]

Page/switch/models.py
from django.db import models

# Create your models here.
class Card(models.Model):
    # card_pk = models.ForeignKey(  ,models.CASCADE)
    img_url = models.URLField(max_length=200,null=True, blank=True)
    image = models.ImageField(upload_to='photos/%Y/%m/%d/', null=True)
    title = models.CharField(max_length=16,null=True, blank=True)
    descriptions = models.CharField(max_length=64, null=True,blank=True)


    def __str__(self) -> str:
        return f"{self.title}"

Page/switch/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Card
# Create your views here.


def home(request):
    cards = Card.objects.all()
    ctx = {  # context
        "cards":cards
    }
    return render(request, 'switch/home.html', ctx)


def card_details(request):
    return render(request, 'switch/card_details.html')

Page/switch/templates/switch/card_details.html
{% comment %} ---------- add olunur bura load static
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

bu cur yazilacaqdir ---------- {% endcomment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class="w3-container">
      <h2>Card Content</h2>
      <p>Add containers inside the card to create different sections:</p>

      <div class="w3-card-4" style="width: 50%">
        <header class="w3-container w3-blue">
          <h1>Header</h1>
        </header>

        <div class="w3-container">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </p>
        </div>

        {%comment %} ---------- href = icerisine app / url icerisindeki path {
        name = '/....' } yazilir ve isdifade edilir ---------- {% endcomment %}
        <a href="{% url 'switch:home-anasehife' %}">Home</a>
        <footer class="w3-container w3-blue">
          <h5>Footer</h5>
        </footer>
      </div>
    </div>
  </body>
</html>

Page/switch/templates/switch/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <style>
      .container {
        width: 90%;
        /* background-color: blue; */
        margin: 20px auto;
      }
      .content {
        display: flex;
        gap: 20px;
      }
      .card {
        width: 350px;
        height: 200px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        transition: 0.3s;
      }
      img {
        width: 100%;
        height: 100%;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
      }

      .bottom-text {
        padding: 2px 16px;
      }
    </style>
  </head>

  <body>
    <h2>Card</h2>
    <div class="container">
      <div class="content">
        {% for card in cards %}
        <a href="{% url 'switch:card-details' %}">
          <div class="card">
            <!-- 

              add: added choose File field  admin input 
              add: img path = card.image.url 
              -->
            <img src="{{ card.image.url }}" alt="Avatar" />
            <div class="bottom-text">
              <h4><b>{{card.title}}</b></h4>
              <p>{{card.descriptions}}</p>
            </div>
          </div>
        </a>
        {% endfor %}
        <!-- create - url's name -->
        {% comment %}
        <a href="{% url 'switch:create' %}"></a>
        {% endcomment %}
      </div>
    </div>
  </body>
</html>